# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

blank_issues_enabled: true
contact_links:
  - name: Ultralytics discussions
    url: https://github.com/orgs/ultralytics/discussions
    about: Ask the broader Ultralytics community.
