// Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

// File and folder icons from the Material Icon Theme (MIT), the set VS Code users read a tree by: each
// language and tool has the mark its own ecosystem uses, so a folder is scannable at a glance. Only the
// icons named below are bundled, and each is served as its own small file rather than inlined, so the
// tree costs the startup bundle a table of names and nothing more.
const ICONS = import.meta.glob<string>(
  "/node_modules/material-icon-theme/icons/{android,assembly,astro,audio,bun,biome,c,cabal,certificate,changelog,clojure,cmake,codeowners,conduct,console,contributing,cpp,csharp,css,cuda,dart,database,dependabot,diff,disc,dll,docker,document,editorconfig,elixir,erlang,eslint,exe,favicon,file,font,fortran,gemfile,git,go,go-mod,gradle,graphql,h,haskell,hex,hpp,html,image,jar,java,javaclass,javascript,jest,json,julia,jupyter,key,kotlin,less,lib,license,lock,log,lua,makefile,markdown,maven,mdx,next,nix,nodejs,npm,objective-c,onnx,pdf,php,pkl,playwright,pnpm,poetry,postcss,powershell,prettier,prisma,proto,python,python-misc,pytorch,r,react,react_ts,readme,robots,ruby,ruff,rust,sass,scala,settings,solidity,svelte,svg,swift,table,tailwindcss,tauri,terraform,test-js,test-jsx,test-ts,tex,toml,tsconfig,tune,typescript,typescript-def,uv,vercel,video,vim,vite,vitest,vue,webassembly,word,xml,yaml,yarn,zig,zip,folder,folder-open,folder-admin,folder-admin-open,folder-android,folder-android-open,folder-animation,folder-animation-open,folder-api,folder-api-open,folder-app,folder-app-open,folder-archive,folder-archive-open,folder-audio,folder-audio-open,folder-backup,folder-backup-open,folder-benchmark,folder-benchmark-open,folder-ci,folder-ci-open,folder-claude,folder-claude-open,folder-class,folder-class-open,folder-client,folder-client-open,folder-components,folder-components-open,folder-config,folder-config-open,folder-container,folder-container-open,folder-context,folder-context-open,folder-controller,folder-controller-open,folder-core,folder-core-open,folder-coverage,folder-coverage-open,folder-css,folder-css-open,folder-database,folder-database-open,folder-debug,folder-debug-open,folder-dist,folder-dist-open,folder-docker,folder-docker-open,folder-docs,folder-docs-open,folder-download,folder-download-open,folder-environment,folder-environment-open,folder-examples,folder-examples-open,folder-export,folder-export-open,folder-features,folder-features-open,folder-font,folder-font-open,folder-generator,folder-generator-open,folder-git,folder-git-open,folder-github,folder-github-open,folder-gitlab,folder-gitlab-open,folder-helper,folder-helper-open,folder-home,folder-home-open,folder-hook,folder-hook-open,folder-husky,folder-husky-open,folder-i18n,folder-i18n-open,folder-images,folder-images-open,folder-import,folder-import-open,folder-include,folder-include-open,folder-input,folder-input-open,folder-intellij,folder-intellij-open,folder-interface,folder-interface-open,folder-ios,folder-ios-open,folder-java,folder-java-open,folder-javascript,folder-javascript-open,folder-job,folder-job-open,folder-json,folder-json-open,folder-jupyter,folder-jupyter-open,folder-keys,folder-keys-open,folder-kotlin,folder-kotlin-open,folder-kubernetes,folder-kubernetes-open,folder-layout,folder-layout-open,folder-lib,folder-lib-open,folder-linux,folder-linux-open,folder-log,folder-log-open,folder-lottie,folder-lottie-open,folder-macos,folder-macos-open,folder-messages,folder-messages-open,folder-meta,folder-meta-open,folder-middleware,folder-middleware-open,folder-migrations,folder-migrations-open,folder-mock,folder-mock-open,folder-node,folder-node-open,folder-packages,folder-packages-open,folder-plugin,folder-plugin-open,folder-private,folder-private-open,folder-public,folder-public-open,folder-python,folder-python-open,folder-queue,folder-queue-open,folder-resource,folder-resource-open,folder-review,folder-review-open,folder-routes,folder-routes-open,folder-rust,folder-rust-open,folder-scripts,folder-scripts-open,folder-secure,folder-secure-open,folder-server,folder-server-open,folder-shared,folder-shared-open,folder-src,folder-src-open,folder-src-tauri,folder-src-tauri-open,folder-store,folder-store-open,folder-svg,folder-svg-open,folder-target,folder-target-open,folder-tasks,folder-tasks-open,folder-temp,folder-temp-open,folder-template,folder-template-open,folder-terraform,folder-terraform-open,folder-test,folder-test-open,folder-tools,folder-tools-open,folder-typescript,folder-typescript-open,folder-ui,folder-ui-open,folder-upload,folder-upload-open,folder-utils,folder-utils-open,folder-video,folder-video-open,folder-views,folder-views-open,folder-vscode,folder-vscode-open,folder-windows,folder-windows-open}.svg",
  { eager: true, query: "?url", import: "default" },
);

function iconUrl(name: string): string | undefined {
  return ICONS[`/node_modules/material-icon-theme/icons/${name}.svg`];
}

// Files a project names rather than extends, which say more than the extension they lack.
const FILE_NAMES: Record<string, string> = {
  ".dockerignore": "docker",
  ".editorconfig": "editorconfig",
  ".env": "tune",
  ".eslintrc": "eslint",
  ".gitattributes": "git",
  ".gitignore": "git",
  ".gitmodules": "git",
  ".npmrc": "npm",
  ".nvmrc": "nodejs",
  ".prettierrc": "prettier",
  ".python-version": "python-misc",
  "biome.json": "biome",
  "bun.lock": "bun",
  "bun.lockb": "bun",
  "cargo.lock": "rust",
  "cargo.toml": "rust",
  "changelog.md": "changelog",
  "cmakelists.txt": "cmake",
  "code_of_conduct.md": "conduct",
  codeowners: "codeowners",
  "compose.yaml": "docker",
  "compose.yml": "docker",
  "contributing.md": "contributing",
  copying: "license",
  "dependabot.yml": "dependabot",
  "docker-compose.yaml": "docker",
  "docker-compose.yml": "docker",
  dockerfile: "docker",
  "favicon.ico": "favicon",
  gemfile: "gemfile",
  "go.mod": "go-mod",
  "go.sum": "go-mod",
  license: "license",
  "license.md": "license",
  "license.txt": "license",
  makefile: "makefile",
  "package-lock.json": "nodejs",
  "package.json": "nodejs",
  "pnpm-lock.yaml": "pnpm",
  "poetry.lock": "poetry",
  "pom.xml": "maven",
  "pyproject.toml": "python-misc",
  "readme.md": "readme",
  "requirements.txt": "python-misc",
  "robots.txt": "robots",
  "ruff.toml": "ruff",
  "security.md": "lock",
  "tauri.conf.json": "tauri",
  "tsconfig.json": "tsconfig",
  "uv.lock": "uv",
  "vercel.json": "vercel",
  "yarn.lock": "yarn",
};

// Extensions read from the longest suffix that names an icon, so app.test.ts is a test before it is
// TypeScript and types.d.ts is a declaration before it is a source file.
const FILE_EXTENSIONS: Record<string, string> = {
  "7z": "zip",
  a: "lib",
  apk: "android",
  asm: "assembly",
  astro: "astro",
  avi: "video",
  avif: "image",
  bash: "console",
  bat: "console",
  bin: "hex",
  bmp: "image",
  bz2: "zip",
  c: "c",
  cabal: "cabal",
  cc: "cpp",
  cer: "certificate",
  cert: "certificate",
  cfg: "settings",
  cjs: "javascript",
  class: "javaclass",
  clj: "clojure",
  cmake: "cmake",
  cmd: "console",
  conf: "settings",
  cpp: "cpp",
  crt: "certificate",
  cs: "csharp",
  css: "css",
  csv: "table",
  cu: "cuda",
  cuh: "cuda",
  cxx: "cpp",
  "d.ts": "typescript-def",
  dart: "dart",
  db: "database",
  diff: "diff",
  dll: "dll",
  dmg: "disc",
  doc: "word",
  docx: "word",
  dockerfile: "docker",
  env: "tune",
  eot: "font",
  erl: "erlang",
  ex: "elixir",
  exe: "exe",
  exs: "elixir",
  f90: "fortran",
  fish: "console",
  flac: "audio",
  gif: "image",
  go: "go",
  gql: "graphql",
  gradle: "gradle",
  graphql: "graphql",
  gz: "zip",
  h: "h",
  hpp: "hpp",
  hs: "haskell",
  htm: "html",
  html: "html",
  icns: "image",
  ico: "image",
  ini: "settings",
  ipynb: "jupyter",
  iso: "disc",
  jar: "jar",
  java: "java",
  jl: "julia",
  jpeg: "image",
  jpg: "image",
  js: "javascript",
  json: "json",
  json5: "json",
  jsonc: "json",
  jsx: "react",
  key: "key",
  kt: "kotlin",
  kts: "kotlin",
  less: "less",
  lock: "lock",
  log: "log",
  lua: "lua",
  m: "objective-c",
  m4a: "audio",
  md: "markdown",
  mdx: "mdx",
  mjs: "javascript",
  mk: "makefile",
  mkv: "video",
  mov: "video",
  mp3: "audio",
  mp4: "video",
  nix: "nix",
  ogg: "audio",
  onnx: "onnx",
  otf: "font",
  parquet: "database",
  patch: "git",
  pdf: "pdf",
  pem: "key",
  php: "php",
  pkl: "pkl",
  plist: "xml",
  png: "image",
  prisma: "prisma",
  proto: "proto",
  ps1: "powershell",
  pt: "pytorch",
  pth: "pytorch",
  py: "python",
  pyc: "python-misc",
  pyi: "python",
  r: "r",
  rar: "zip",
  rb: "ruby",
  rs: "rust",
  rst: "markdown",
  s: "assembly",
  sass: "sass",
  scala: "scala",
  scss: "sass",
  sh: "console",
  so: "dll",
  sol: "solidity",
  "spec.js": "test-js",
  "spec.jsx": "test-jsx",
  "spec.ts": "test-ts",
  "spec.tsx": "test-jsx",
  sql: "database",
  sqlite: "database",
  sqlite3: "database",
  svelte: "svelte",
  svg: "svg",
  swift: "swift",
  tar: "zip",
  "test.js": "test-js",
  "test.jsx": "test-jsx",
  "test.ts": "test-ts",
  "test.tsx": "test-jsx",
  tex: "tex",
  tf: "terraform",
  tgz: "zip",
  tif: "image",
  tiff: "image",
  toml: "toml",
  ts: "typescript",
  tsv: "table",
  tsx: "react_ts",
  ttf: "font",
  txt: "document",
  vim: "vim",
  vue: "vue",
  wasm: "webassembly",
  wav: "audio",
  webm: "video",
  webp: "image",
  whl: "python-misc",
  woff: "font",
  woff2: "font",
  xls: "table",
  xlsx: "table",
  xml: "xml",
  xz: "zip",
  yaml: "yaml",
  yml: "yaml",
  zig: "zig",
  zip: "zip",
  zsh: "console",
};

// Files a tool names by its own convention, matched on the whole name after the exact names above.
const FILE_PATTERNS: [RegExp, string][] = [
  [/^dockerfile\./, "docker"],
  [/^tailwind\.config\./, "tailwindcss"],
  [/^postcss\.config\./, "postcss"],
  [/^eslint\.config\./, "eslint"],
  [/^prettier\.config\./, "prettier"],
  [/^vite\.config\./, "vite"],
  [/^vitest\.config\./, "vitest"],
  [/^jest\.config\./, "jest"],
  [/^playwright\.config\./, "playwright"],
  [/^next\.config\./, "next"],
  [/^tsconfig\..*\.json$/, "tsconfig"],
  [/^\.env\./, "tune"],
  [/^requirements[-.].*\.txt$/, "python-misc"],
];

const FOLDER_NAMES: Record<string, string> = {
  ".cache": "temp",
  ".claude": "claude",
  ".git": "git",
  ".github": "github",
  ".gitlab": "gitlab",
  ".husky": "husky",
  ".idea": "intellij",
  ".venv": "environment",
  ".vscode": "vscode",
  __tests__: "test",
  admin: "admin",
  android: "android",
  animation: "animation",
  animations: "animation",
  api: "api",
  app: "app",
  apps: "app",
  archive: "archive",
  assets: "resource",
  audio: "audio",
  auth: "secure",
  backend: "server",
  backup: "backup",
  benchmark: "benchmark",
  benchmarks: "benchmark",
  bin: "dist",
  build: "dist",
  cache: "temp",
  cargo: "rust",
  certs: "secure",
  ci: "ci",
  client: "client",
  cluster: "kubernetes",
  common: "shared",
  components: "components",
  config: "config",
  configs: "config",
  container: "container",
  containers: "container",
  context: "context",
  controllers: "controller",
  core: "core",
  coverage: "coverage",
  css: "css",
  data: "database",
  database: "database",
  db: "database",
  debug: "debug",
  dependencies: "packages",
  dist: "dist",
  doc: "docs",
  docker: "docker",
  docs: "docs",
  download: "download",
  downloads: "download",
  e2e: "coverage",
  env: "environment",
  environment: "environment",
  environments: "environment",
  example: "examples",
  examples: "examples",
  export: "export",
  exports: "export",
  features: "features",
  fixtures: "mock",
  font: "font",
  fonts: "font",
  frontend: "client",
  generators: "generator",
  helper: "helper",
  helpers: "helper",
  home: "home",
  hooks: "hook",
  i18n: "i18n",
  icons: "images",
  images: "images",
  img: "images",
  import: "import",
  imports: "import",
  include: "include",
  input: "input",
  interfaces: "interface",
  ios: "ios",
  java: "java",
  jobs: "job",
  js: "javascript",
  json: "json",
  jupyter: "jupyter",
  k8s: "kubernetes",
  keys: "keys",
  kotlin: "kotlin",
  kubernetes: "kubernetes",
  layout: "layout",
  layouts: "layout",
  lib: "lib",
  libs: "lib",
  linux: "linux",
  locales: "i18n",
  log: "log",
  logs: "log",
  lottie: "lottie",
  macos: "macos",
  messages: "messages",
  meta: "meta",
  middleware: "middleware",
  migrations: "migrations",
  mock: "mock",
  mocks: "mock",
  model: "class",
  models: "class",
  modules: "plugin",
  node_modules: "node",
  notebooks: "jupyter",
  out: "dist",
  output: "dist",
  packages: "packages",
  pages: "views",
  plugins: "plugin",
  private: "private",
  providers: "controller",
  public: "public",
  python: "python",
  queue: "queue",
  release: "dist",
  resource: "resource",
  resources: "resource",
  review: "review",
  routes: "routes",
  rust: "rust",
  scripts: "scripts",
  secrets: "keys",
  secure: "secure",
  server: "server",
  services: "controller",
  shared: "shared",
  site: "public",
  spec: "test",
  src: "src",
  "src-tauri": "src-tauri",
  static: "resource",
  store: "store",
  styles: "css",
  svg: "svg",
  target: "target",
  tasks: "tasks",
  temp: "temp",
  template: "template",
  templates: "template",
  terraform: "terraform",
  test: "test",
  tests: "test",
  tmp: "temp",
  tools: "tools",
  types: "typescript",
  typescript: "typescript",
  typings: "typescript",
  ui: "ui",
  upload: "upload",
  uploads: "upload",
  util: "utils",
  utils: "utils",
  vendor: "lib",
  venv: "environment",
  video: "video",
  videos: "video",
  views: "views",
  web: "public",
  windows: "windows",
  www: "public",
};

function fileIconName(lower: string): string {
  const named = FILE_NAMES[lower] ?? FILE_PATTERNS.find(([pattern]) => pattern.test(lower))?.[1];
  if (named) return named;
  const parts = lower.split(".");
  for (let start = 1; start < parts.length; start++) {
    const icon = FILE_EXTENSIONS[parts.slice(start).join(".")];
    if (icon) return icon;
  }
  return "file";
}

export function FileIcon({ name, directory, open }: { name: string; directory?: boolean; open?: boolean }) {
  const lower = name.toLowerCase();
  const icon = directory
    ? `folder${FOLDER_NAMES[lower] ? `-${FOLDER_NAMES[lower]}` : ""}${open ? "-open" : ""}`
    : fileIconName(lower);
  return <img src={iconUrl(icon) ?? iconUrl("file")} alt="" aria-hidden="true" className="size-4 shrink-0" />;
}
